### ISSUE TITLE
Duplicate mini reverb

### ISSUE THREAD

**Issue by nodep** [mstratman/fv1-programs#21]
Hi,

I don't want to be a knitpicker, and you probably already know about this, but you have the same program (min_rev1.spn) in two different locations:

1. https://github.com/mstratman/fv1-programs/tree/master/static/files/min_rev1.spn
2. https://github.com/mstratman/fv1-programs/tree/master/static/files/spinsemi/min_rev1.spn

Thanks for this amazing archive!

**Comment by mstratman** [comment]
Thanks for the heads up. That was definitely an oversight. It should be fixed now.
